### PR TITLE
Add fix and changelog note

### LINKED ISSUE #3: s6-overlay-suexec: fatal: can only run as pid 1
Seems to be related to the latest version of HA: [HA Breaking Changes](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/)

### PR DESCRIPTION
**Pull request by Didainius**
This pull request fixes #3 and adds compatibility with latest Home Assistant versions

### CODE REVIEW

**Comment by mboettcher** [comment]
@MickMake Would be great if you could check this and merge it.

**Comment by Thibaut1976** [comment]
I have the same issue

**Comment by andpar-private** [comment]
Same issue here

**Comment by pzutenis** [comment]
Me too ! Same issue - has this project been abandoned ? Its just what I need after my efergy system died...... please merge (merge request submitted in june ?) - doesnt seem to be an 'easy' way in haos to modify the file directly.....

**Comment by mboettcher** [comment]
Since this seems abandoned.

For anyone ending up here as well like me: I found https://github.com/mkaiser/Sungrow-SHx-Inverter-Modbus-Home-Assistant which works great with a direct LAN connection via Modbus

**Comment by MickMake** [comment]
Hi, definitely not abandoned.
I've been working on v3 of GoSungrow before updating this hassio addon.
V3 is a major update that adds a lot of features.

**Pull request closed without merging**
